version: '3'

services:

### Workspace Utilities Container #######

  workspace:
    build:
      args:
        - VERSION=${WORKSPACE_VERSION_PHP}
      #   - COMPOSER_GLOBAL_INSTALL=${WORKSPACE_COMPOSER_GLOBAL_INSTALL}
      #   - PUID=${WORKSPACE_PUID}
      #   - PGID=${WORKSPACE_PGID}
      #   - TZ=${WORKSPACE_TIMEZONE}
      #   - PHP_INSTALL_APCU=${PHP_INSTALL_APCU}
      #   - PHP_INSTALL_APCU_BC=${PHP_INSTALL_APCU_BC}
      #   - PHP_INSTALL_OPCACHE=${PHP_INSTALL_OPCACHE}
      context: ./workspace
    networks:
      - backend
      - frontend
    tty: true
    volumes:
      - ${APPLICATION}:/var/www

networks:
  backend:
  frontend:
