version: '3'

services:

### Workspace Utilities Container #######

  workspace:
    build:
      args:
        - NODE_VERSION=${WORKSPACE_NODE_VERSION}
        - NVM_VERSION=${WORKSPACE_NVM_VERSION}
        - PHPUNIT_VERSION=${WORKSPACE_PHPUNIT_VERSION}
        - VERSION=${WORKSPACE_PHP_VERSION}

      #   - PUID=${WORKSPACE_PUID}
      #   - PGID=${WORKSPACE_PGID}
      context: ./workspace
    networks:
      - backend
      - frontend
    tty: true
    volumes:
      - ${APPLICATION}:/var/www

networks:
  backend:
  frontend:
