#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#

FROM php:7.1-fpm

MAINTAINER Pierre-Louis Launay <laupi.frpar@gmail.com>

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    curl \
    libmemcached-dev \
    libz-dev \
    libpq-dev \
    libjpeg-dev \
    libpng12-dev \
    libfreetype6-dev \
    libssl-dev \
    libmcrypt-dev \
    libmagickwand-dev \
    imagemagick \
  && rm -rf /var/lib/apt/lists/*

# Install the PHP mcrypt extention
RUN docker-php-ext-install mcrypt pdo_mysql zip bcmath \
  && docker-php-ext-configure gd \
    --enable-gd-native-ttf \
    --with-jpeg-dir=/usr/lib \
    --with-freetype-dir=/usr/include/freetype2 \
  && docker-php-ext-install gd

#####################################
# OPCACHE - APCU
#####################################
ARG INSTALL_OPCACHE=false
ARG INSTALL_APCU=false
RUN if [ ${INSTALL_OPCACHE} = true ] && [ ${INSTALL_APCU} = false]; then \
    docker-php-ext-install opcache \
;fi
COPY ./opcache.ini /usr/local/etc/php/conf.d/opcache.ini

RUN if [ ${INSTALL_OPCACHE} = false ] && [ ${INSTALL_APCU} = true ]; then \
    pecl -vvv install apcu && \
    docker-php-ext-enable apcu \
;fi
COPY ./apcu.ini /usr/local/etc/php/conf.d/apcu.ini

ARG INSTALL_APCU_BC=false
RUN if [ ${INSTALL_OPCACHE} = false ] && [ ${INSTALL_APCU} = true ] && [ ${INSTALL_APCU_BC} = true ]; then \
    pecl -vvv install apcu_bc && \
    docker-php-ext-enable apcu_bc \
;fi

#####################################
# PHP REDIS EXTENSION FOR PHP 7.0
#####################################

RUN pecl install -o -f redis \
    &&  rm -rf /tmp/pear \
    &&  docker-php-ext-enable redis

#####################################
# Human Language and Character Encoding Support:
#####################################

ARG INSTALL_ICU_VERSION=60.1
ENV PHP_CPPFLAGS="$PHP_CPPFLAGS -std=c++11"
RUN curl -fsS -o /tmp/icu.tgz -L http://download.icu-project.org/files/icu4c/${INSTALL_ICU_VERSION}/icu4c-$(echo $INSTALL_ICU_VERSION | sed 's/\./_/')-src.tgz \
	&& tar -zxf /tmp/icu.tgz -C /tmp \
	&& cd /tmp/icu/source \
	&& ./configure --prefix=/usr/local \
	&& make \
	&& make install \
	&& rm -rf /tmp/icu* \
	&& docker-php-ext-configure intl --with-icu-dir=/usr/local \
	&& docker-php-ext-install intl

#####################################
# ImageMagick:
#####################################
USER root
RUN pecl install imagick \
	&& docker-php-ext-enable imagick

ADD ./custom.ini /usr/local/etc/php/conf.d

RUN usermod -u 1000 www-data

WORKDIR /var/www

CMD ["php-fpm"]

EXPOSE 9000
